language: php

php:
  - 5.6
  - 5.5

cache:
  directories:
    - $HOME/.composer/cache

before_install:
   - composer validate

install:
   - composer install

script:
  - vendor/bin/phpunit --verbose --coverage-clover ./build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v
