language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
before_script:
   - composer install
script: "phpunit --verbose --coverage-clover ./build/logs/clover.xml"
after_script:
  - php vendor/bin/coveralls -v
